# Generated by Django 3.1.5 on 2021-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=60)),
                ('priority', models.CharField(max_length=60)),
                ('duedate', models.DateField(null=True)),
                
            ],
        ),
    ]
